DROP DATABASE IF EXISTS `Person`;

CREATE DATABASE `Person`;

USE `Person`;

CREATE TABLE `PersonDetail`
 (
    `Id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `Name` VARCHAR(50) NOT NULL,
    `EMAILID` VARCHAR(50)NOT NULL,
    `MOBILENUMBER` VARCHAR(50) NOT NULL,
    `PASSWORD` VARCHAR(50) NOT NULL,
    `ADDRESS` VARCHAR(50)NOT NULL
);